//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAssignment03
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPhone
    {
        public int ContactPhoneId { get; set; }
        public int ContactId { get; set; }
        public int PhoneId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual PhoneNumber PhoneNumber { get; set; }
    }
}
